services:
  comic-vault:
    build: .
    container_name: comic-vault 
    ports:
      - "25000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://comic-vault-db:27017/comic_vault
    depends_on:
      - comic-vault-db
    volumes:
      - ${COMICS_VOLUME_PATH:-${HOME}/Comics}:/data/comics
    networks:
      - comic-vault-network

  comic-vault-db:
    image: mongo:4.4.22
    container_name: comic-vault-db
    volumes:
      - mongo-data:/data/db
    networks:
      - comic-vault-network

networks:
  comic-vault-network:

volumes:
  mongo-data:

