services:
  comic-vault:
    build:
      context: .
      target: production
    container_name: comic-vault
    ports:
      - "25000:5000"
    environment:
      - MONGO_URI=mongodb://comic-vault-db:27017/comic_vault
      - FLASK_DEBUG=0
    volumes:
      - ${COMICS_VOLUME_PATH:-${HOME}/Comics}:/data/comics
    command: gunicorn -b 0.0.0.0:5000 run:app --workers 4
    depends_on:
      - comic-vault-db
    networks:
      - comic-vault-network

  comic-vault-db:
    image: mongo:4.4.22
    container_name: comic-vault-db
    volumes:
      - mongo-data:/data/db
    networks:
      - comic-vault-network

networks:
  comic-vault-network:

volumes:
  mongo-data:
